services:
  api:
    build:
      context: .
    container_name: api
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    command: npm run dev
    depends_on:
      - db
  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx/conf
    depends_on:
      - api
      - db

volumes:
  mongo-data:
