services:
  api:
    build:
      context: .
    container_name: api
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000
    command: npm run dev
    depends_on:
      - db
  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  reverse-proxy:
    image: traefik:v3.1
    container_name: reverse-proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run.sock

volumes:
  mongo-data:
